<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<link rel="stylesheet" href="<?=base_url()?>src/css/all.min.css">
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="<?=base_url()?>src/css/tempusdominus-bootstrap-4.min.css">
<link rel="stylesheet" href="<?=base_url()?>src/css/icheck-bootstrap.min.css">
<link rel="stylesheet" href="<?=base_url()?>src/css/jqvmap.min.css">
<link rel="stylesheet" href="<?=base_url()?>src/css/adminlte.min.css">
<link rel="stylesheet" href="<?=base_url()?>src/css/OverlayScrollbars.min.css">
<link rel="stylesheet" href="<?=base_url()?>src/css/daterangepicker.css">
<link rel="stylesheet" href="<?=base_url()?>src/css/summernote-bs4.min.css">
<link rel="stylesheet" href="<?=base_url()?>src/css/fontawesome.css">
